### ISSUE TITLE
sing-box的配置文件，服务端禁止访问IP，无效？

### ISSUE THREAD

**Issue by chika0801** [FranzKafkaYu/sing-box-yes#1]
我使用你的ss2022配置

https://github.com/FranzKafkaYu/sing-box-yes/blob/main/shadowsocks2022/server_config.json

我客户端是全局代理，发现CN IP的网站打得开。

我自己看sing-box文档尝试写了一个也是无效的

https://github.com/SagerNet/sing-box/issues/96

请问你那有测试过 禁 CN IP这规则 吗？

**Comment by FranzKafkaYu** [comment]
> 我使用你的ss2022配置
> 
> https://github.com/FranzKafkaYu/sing-box-yes/blob/main/shadowsocks2022/server_config.json
> 
> 我客户端是全局代理，发现CN IP的网站打得开。
> 
> 我自己看sing-box文档尝试写了一个也是无效的
> 
> [SagerNet/sing-box#96](https://github.com/SagerNet/sing-box/issues/96)
> 
> 请问你那有测试过 禁 CN IP这规则 吗？

我测试没有问题的，在客户端路由规则了cn是直连，你可以确认一下：
![image](https://user-images.githubusercontent.com/38254177/190867413-07cd8fe5-e8b5-42a5-a8f5-3be29b16be94.png)

**Comment by chika0801** [comment]
已解决3QU
