### ISSUE TITLE
最新版本的sing-box 1.1-beta17无法更新

### ISSUE THREAD

**Issue by mliyuanbiao** [FranzKafkaYu/sing-box-yes#13]
https://github.com/SagerNet/sing-box/releases/download/1.1-beta17/sing-box-1.1-beta17-linux-amd64.tar.gz

https://github.com/SagerNet/sing-box/releases/download/v1.0.7/sing-box-1.0.7-linux-amd64.tar.gz

可以看到1.1-beta17是不带v的v1.0.7是带v的，官方的下载链接存在这两种情况，希望能兼容一下这两种情况。目前1.1-beta17无法更新

**Comment by FranzKafkaYu** [comment]
> https://github.com/SagerNet/sing-box/releases/download/1.1-beta17/sing-box-1.1-beta17-linux-amd64.tar.gz
> 
> https://github.com/SagerNet/sing-box/releases/download/v1.0.7/sing-box-1.0.7-linux-amd64.tar.gz
> 
> 可以看到1.1-beta17是不带v的v1.0.7是带v的，官方的下载链接存在这两种情况，希望能兼容一下这两种情况。目前1.1-beta17无法更新

收到，感谢反馈，晚点看看

**Comment by AtoiX** [comment]
不光17 好像所有beta都不能指定了

**Comment by FranzKafkaYu** [comment]
> 不光17 好像所有beta都不能指定了

@AtoiX 可以指定的，测试没有问题，但是1.1-beta17确实无法更新，因为上游更改了下载链接（看上去像是手动的），看看下个beta版本是否会恢复过来。
