### ISSUE TITLE
sing-box-yes Naiveproxy服务端配置模板

### ISSUE THREAD

**Issue by okoklai** [FranzKafkaYu/sing-box-yes#17]
{
    "log": {
        "disabled": false,
        "level": "info",
        "output": "/usr/local/sing-box/sing-box.log",
        "timestamp": true
    },
    "dns": {
        "servers": [
            {
                "tag": "google-tls",
                "address": "local",
                "address_strategy": "prefer_ipv4",
                "strategy": "ipv4_only",
                "detour": "direct"
            },
            {
                "tag": "google-udp",
                "address": "8.8.8.8",
                "address_strategy": "prefer_ipv4",
                "strategy": "prefer_ipv4",
                "detour": "direct"
            }
        ],
        "strategy": "prefer_ipv4",
        "disable_cache": false,
        "disable_expire": false
    },
    "inbounds": [
		{
			"type": "naive",
			"tag": "naive-in",
			"listen_port": 10240,
			"sniff": true,
			"sniff_override_destination": true,
			"sniff_timeout": "300ms",
			"users": [
				{
					"username": "yourloginname",
					"password": "yourpassword"
				}
			],
			"tls": {
				"enabled": true,
				"server_name": "youdomain.com",
				"certificate_path": "/root/youdomain.com/fullchain.cer",
				"key_path": "/root/youdomain.com/youdomain.com.key"
			}
		}
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "type": "block",
            "tag": "block"
        },
        {
            "type": "dns",
            "tag": "dns-out"
        }
    ],
    "route": {
        "rules": [
            {
                "protocol": "dns",
                "outbound": "dns-out"
            },
            {
                "inbound": [
                    "naive-in"
                ],
                "network": "tcp",
                "outbound": "direct"
            },
            {
                "geosite": "category-ads-all",
                "outbound": "block"
            },
            {
                "geosite": "cn",
                "geoip": "cn",
                "outbound": "block"
            }
        ],
        "geoip": {
            "path": "geoip.db",
            "download_url": "https://github.com/SagerNet/sing-geoip/releases/latest/download/geoip.db",
            "download_detour": "direct"
        },
        "geosite": {
            "path": "geosite.db",
            "download_url": "https://github.com/SagerNet/sing-geosite/releases/latest/download/geosite.db",
            "download_detour": "direct"
        },
        "final": "direct",
        "auto_detect_interface": true
    }
}

**Comment by FranzKafkaYu** [comment]
@okoklai 感谢~
