### ISSUE TITLE
combining x-ui panel with singbox core

### ISSUE THREAD

**Issue by epsilonzeio** [FranzKafkaYu/sing-box-yes#22]
I'd like to use your panel in order to use multi users with reality protocol and singbox core. 
Just want to know if your current panel in github supports this.
If not, I wanted to ask you kindly to combine the signbox core with your x-ui panel to be able to use reality with multi users and the lowest ping possible (due to singbox core) 

thanks in advance

**Comment by FailedTech** [comment]
Yea this is cool we really need this..

**Comment by FranzKafkaYu** [comment]
Sorry I have no time to do this work.

**Comment by master88wi** [comment]
+1
