### ISSUE TITLE
can't finish installtion. there is an error report.

### ISSUE THREAD

**Issue by needhumanity** [FranzKafkaYu/sing-box-yes#23]
[INF] sing-box状态: 未安装

请输入选择[0-G]:1
[DEG] 开始安装sing-box... 
[DEG] 开始下载sing-box... 
[INF] 检测当前系统中... 
[INF] 系统检测完毕,当前系统为:ubuntu 
[INF] 检测当前系统架构中... 
[INF] 当前系统架构为 aarch64 
[INF] 系统架构检测完毕,当前系统架构为:arm64 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tar is already the newest version (1.30+dfsg-7ubuntu0.20.04.3).
wget is already the newest version (1.20.3-1ubuntu2).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 90 not upgraded.
[INF] 将选择使用版本: 
[INF] Will create /usr/local/sing-box and /usr/local/etc/sing-box for sing-box... 
[INF] create /usr/local/sing-box adn /usr/local/etc/sing-box for sing-box success 
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2023-06-30 09:55:26--  https://github.com/SagerNet/sing-box/releases/download//sing-box--linux-arm64.tar.gz
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-30 09:55:27 ERROR 404: Not Found.

[ERR] Download sing-box failed,plz be sure that your network work properly and can access github 
[INF] Will delete /usr/local/sing-box and /usr/local/etc/sing-box... 
[INF] delete /usr/local/sing-box and /usr/local/etc/sing-box success

**Comment by FranzKafkaYu** [comment]
@needhumanity  Got it,I will make a test later.

**Comment by FranzKafkaYu** [comment]
@needhumanity sorry,I have made a test while It worked perfectly in my server，plz check this command excution and show me the result：  
```
curl -Ls "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'    
```  

here is mine test result:  
```
root@bwg29cn2:/home/FranzKafka# curl -Ls "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
v1.3.0
root@bwg29cn2:/home/FranzKafka# 
```
