### ISSUE TITLE
服务自动退出

### ISSUE THREAD

**Issue by ydqsbfsyi** [FranzKafkaYu/sing-box-yes#7]
本来试了手动安装，发现服务总是自动退出。后来发现了这个一键脚本，然后也是同样的错误：
systemd[1]: sing-box.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: sing-box.service: Failed with result 'exit-code'.

安装时候说成功。但实际上没有，并且再也启动不了了。
是不是纯ipv6不行，需要warp？

**Comment by FranzKafkaYu** [comment]
> 本来试了手动安装，发现服务总是自动退出。后来发现了这个一键脚本，然后也是同样的错误： systemd[1]: sing-box.service: Main process exited, code=exited, status=1/FAILURE systemd[1]: sing-box.service: Failed with result 'exit-code'.
> 
> 安装时候说成功。但实际上没有，并且再也启动不了了。 是不是纯ipv6不行，需要warp？

请通过查看日志功能查看具体的报错原因，另外是否有使用配置检查功能?如果可以的话请提供一下日志。

**Comment by ydqsbfsyi** [comment]
> > 本来试了手动安装，发现服务总是自动退出。后来发现了这个一键脚本，然后也是同样的错误： systemd[1]: sing-box.service: Main process exited, code=exited, status=1/FAILURE systemd[1]: sing-box.service: Failed with result 'exit-code'.
> > 安装时候说成功。但实际上没有，并且再也启动不了了。 是不是纯ipv6不行，需要warp？
> 
> 请通过查看日志功能查看具体的报错原因，另外是否有使用配置检查功能?如果可以的话请提供一下日志。

谢谢答复。
我上面帖的代码，就是查看日志，我帖一下完整的：
`Sep 27 00:56:52 606672145hax.localdomain systemd[1]: Started sing-box service.
Sep 27 00:56:52 606672145hax.localdomain sing-box[118596]: FATAL[0000] create service: parse inbound[0]: read certificate: open /root/fullchain.cer: no such file or directory
Sep 27 00:56:52 606672145hax.localdomain systemd[1]: sing-box.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 00:56:52 606672145hax.localdomain systemd[1]: sing-box.service: Failed with result 'exit-code'.
Sep 27 00:57:02 606672145hax.localdomain systemd[1]: sing-box.service: Scheduled restart job, restart counter is at 5569.
Sep 27 00:57:02 606672145hax.localdomain systemd[1]: Stopped sing-box service.
Sep 27 00:57:02 606672145hax.localdomain systemd[1]: Started sing-box service.
.........
`

配置检查功能的结果：
`[INF] 版本信息:sing-box 1.0.5.3105b8c (go1.19.1, linux/amd64, CGO disabled) 
[INF] sing-box状态: 未运行
[INF] sing-box是否开机自启: 是
[INF] 配置文件路径:/usr/local/etc/sing-box/config.json 
[INF] 可执行文件路径:/usr/local/bin/sing-box 
`

**Comment by FranzKafkaYu** [comment]
很明显，你的证书路径有误，请根据实际情况填写:read certificate: open /root/fullchain.cer: no such file or directory

**Comment by ydqsbfsyi** [comment]
谢谢
