### ISSUE TITLE
ss默认配置只改了端口，无法启动sing-box

### ISSUE THREAD

**Issue by lin1123** [FranzKafkaYu/sing-box-yes#8]
sing-box check -c config.json没问题
sing-box run 显示
FATAL[0000] start service: address family not supported by protocol

**Comment by FranzKafkaYu** [comment]
> sing-box check -c config.json没问题 sing-box run 显示 FATAL[0000] start service: address family not supported by protocol

服务端还是客户端?什么系统?

**Comment by lin1123** [comment]
> > sing-box check -c config.json没问题 sing-box run 显示 FATAL[0000] start service: address family not supported by protocol
> 
> 服务端还是客户端?什么系统?

服务端 Debian11
